services:

  socat:
    image: alpine/socat
    ports:
      - "0:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,reuseaddr,fork unix-connect:/var/run/docker.sock
