name: "Release"

on:
  push:
    tags:
      - "*"

jobs:

  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:

      - name: "Docker Buildx setup"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Image tagging"
        # language=sh
        run: >
          DOCKERHUB_IMAGE=${{ github.repository }}
          VERSION=${{ github.ref_name }}

          docker buildx imagetools create
          --tag ${DOCKERHUB_IMAGE}:${VERSION}
          ${DOCKERHUB_IMAGE}:latest

          docker buildx imagetools create
          --tag ${DOCKERHUB_IMAGE}:${VERSION}-alpine
          ${DOCKERHUB_IMAGE}:alpine
